package testing_extra;

import org.testng.Reporter;
import org.testng.annotations.Test;

public class DemoTest {
	
//	Reporter class : This class is used for test methods to log messages 
//	that will be included in the HTML reports generated by TestNG.
	
	@Test
	public void case1() {
	
		System.out.println("Hey There");

	}
	
	@Test
	public void case2() {
		
		Reporter.log("Case 2 : Please go ElseWhere......."); //report
	}
	
	@Test
	public void case3()
	{
		Reporter.log("Case 3 : Please go ElseWhere..........", true); // report + console
	}
}
